name: Java Application Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and Run
        run: |
          mvn clean install
          java -cp target/SoftwareEngineerTest-1.0-SNAPSHOT.jar com.example.ecommerce.Main
